MODD_CONFIO__ = { # I/O file type
    "LCDF4"           : ".TRUE.",
    "LLFIOUT"         : ".FALSE.",
    "LLFIREAD"        : ".FALSE.",
}

MODD_CONFZ__  = { # parallelism
  "MPI_BUFFER_SIZE"   : "400",
}

MODD_BACKUP__ = { # backup files for restarts
  "XBAK_TIME_FREQ(1)" : "3600.0",
}

SURF_IDEAL_FLUX__ = { # surfex default namelist
  "NFORCF"            : "2",
  "NFORCT"            : "2",
  "XTIMEF"            : "0",
  "XTIMET"            : "0",
  "XSFTH"             : "0.",
  "CSFTQ"             : "'kg/m2/s'",
  "XSFTQ"             : "0.",
  "CUSTARTYPE"        : "Z0",
  "XUSTAR"            : "0.",
  "XZ0"               : "0.01",
  "XTSRAD"            : "273.15K",
}

MODD_CONF__   = { # general config
  "CCONF"             :"'START'",
  "LTHINSHELL"        : ".FALSE.",
  "L2D"               : ".FALSE.",
  "L1D"               : ".FALSE.",
  "LFLAT"             : ".FALSE.",
  "NMODEL"            : "1",
  "CEQNSYS"           : "'DUR'",
  "NVERB"             : "5",
  "CEXP"              : "'EXP01'",
  "CSEG"              : "'SEG01'",
  "LFORCING"          : ".FALSE.",
  "L2D_ADV_FRC"       : ".FALSE.",
  "L2D_REL_FRC"       : ".FALSE. ",
  "XRELAX_HEIGHT_BOT" : "0.",
  "XRELAX_HEIGHT_TOP" : "30000.",
  "XRELAX_TIME"       : "864000.",
  "LPACK"             : ".TRUE.",
  "NHALO"             : "1",
  "CSPLIT"            :"'BSPLITTING'",
  "NZ_PROC"           : "0",
  "NZ_SPLITTING"      : "10",
  "LLG"               : ".FALSE.",
  "LINIT_LG"          : ".FALSE.",
  "CINIT_LG"          : "'FMOUT'",
  "LNOMIXLG"          : ".FALSE.",
  "LCHECK"            : ".FALSE.",
}

MODD_CONFn__  = { # config for model n (nesting)
  "CCLOUD"            : "'NONE'",
  "LUSERV"            : ".TRUE.",
  "LUSERC"            : ".FALSE.",
  "LUSERR"            : ".FALSE.",
  "LUSERI"            : ".FALSE.",
  "LUSERS"            : ".FALSE.",
  "LUSERG"            : ".FALSE.",
  "LUSERH"            : ".FALSE.",
  "LOCEAN"            : ".FALSE.",
  "LUSECI"            : ".FALSE.",
}

MODD_FRC__    = {   # forcings
  "LGEOST_UV_FRC"     : ".FALSE.",
  "LGEOST_TH_FRC"     : ".FALSE.",
  "LTEND_THRV_FRC"    : ".FALSE.",
  "LTEND_UV_FRC"      : ".FALSE.", 
  "LVERT_MOTION_FRC"  : ".FALSE.",
  "LRELAX_THRV_FRC"   : ".FALSE.",
  "LRELAX_UV_FRC"     : ".FALSE.",
  "LRELAX_UVMEAN_FRC" : ".FALSE.",
  "XRELAX_TIME_FRC"   : "10800.",
  "XRELAX_HEIGHT_FRC" : "0.",
  "CRELAX_HEIGHT_TYPE": "'FIXE'",
  "LTRANS"            : ".FALSE.",
  "XUTRANS"           : "0.0",
  "XVTRANS"           : "0.0",
  "LPGROUND_FRC"      : ".FALSE.",
  "LDEEPOC"           : ".FALSE.",
  "XCENTX_OC"         : "16000.",
  "XCENTY_OC"         : "16000.",
  "XRADX_OC"          :  "8000.",  
  "XRADY_OC"          :  "8000.",
}

MODD_LBCn__   = {  # boundary conditions for model n
  "CLBCX(1)"          :"'CYCL'",
  "CLBCX(2)"          :"'CYCL'",
  "CLBCY(1)"          :"'CYCL'",
  "CLBCY(2)"          :"'CYCL'",
  "NLBLX(:)"          : "1",
  "NLBLY(:)"          : "1",
  "XCPHASE"           : "20.",
  "XCPHASE_PBL"       : "0.",
  "XPOND"             : "1.0",
}

MODD_DYN__    = { # general dynamics
  "XSEGLEN"           : "43200.",
  "XASSELIN"          : "0.2",
  "XASSELIN_SV"       : "0.02",
  "LCORIO"            : ".TRUE.",
  "LNUMDIFU"          : ".TRUE.",
  "LNUMDIFTH"         : ".FALSE.",
  "LNUMDIFSV"         : ".FALSE.",
  "XALZBOT"           : "4000.",
  "XALKTOP"           : "0.01",
  "XALKGRD"           : "0.01",
  "XALZBAS"           : "0.01",
}

MODD_DYNn__   = { # dynamics for model n (nesting)
  "XTSTEP"            : "60.",
  "CPRESOPT"          : "'CRESI'",
  "NITR"              : "4",
  "LITRADJ"           : ".TRUE.",
  "LRES"              : ".FALSE.",
  "XRES"              : "1.E-07",
  "XRELAX"            : "1.",
  "LVE_RELAX"         : ".FALSE.",
  "LVE_RELAX_GRD"     : ".FALSE.",
  "XT4DIFU"           : "1800.",
  "XT4DIFTH"          : "1800.",
  "XT4DIFSV"          : "1800.",
}

MODD_ADVn__   = { # advection for model n
  "CUVW_ADV_SCHEME"   : "'CEN4TH'",
  "CMET_ADV_SCHEME"   : "'PPM_01'",
  "CSV_ADV_SCHEME"    : "'PPM_01'",
  "CTEMP_SCHEME"      : "'RKC4'",
  "NWENO_ORDER"       : "3",
  "NSPLIT"            : "1",
  "LSPLIT_CFL"        : ".TRUE.",
  "LSPLIT_WENO"       : ".TRUE.",
  "XSPLIT_CFL"        : "0.8",
  "LCFL_WRIT"         : ".FALSE.",
}

MODD_PARAMn__ = { # activate params for model n
  "CTURB"             : "'NONE'",
  "CRAD"              : "'NONE'",
  "CDCONV"            : "'NONE'",
  "CSCONV"            : "'NONE'",
  "CELEC"             : "'NONE'",
  "CACTCCN"           : "'NONE'",
}

MODD_TURBn__  = { # config turbulence
  "XIMPL"             : "1.",
  "XKEMIN"            : "0.01",
  "XCEDIS"            : "0.84",
  "XCADAP"            : "0.5",
  "CTURBLEN"          : "'BL89'",
  "CTURBDIM"          : "'1DIM'",
  "LTURB_FLX"         :".FALSE.",
  "LTURB_DIAG"        :".FALSE.",
  "LSUBG_COND"        :".FALSE.",
  "CSUBG_AUCV"        :"'NONE'", 
  "CSUBG_AUCV_RI"     :"'NONE'",
  "LSIGMAS"           :".TRUE.",
  "LSIG_CONV"         :".FALSE.",
  "LRMC01"            :".FALSE.",
  "CTOM"              :"'NONE'",
  "VSIGQSAT"          : "0.02",
  "CCONDENS"          :"'CB02'",
  "CLAMBDA3"          :"'CB'",
  "CSUBG_MF_PDF"      :"'TRIANGLE'",
  "LLEONARD"          :".FALSE.",
  "XCOEFHGRADTHL"     : "1.0",
  "XCOEFHGRADRM"      : "1.0",
  "XALTHGRAD"         : "2000.0",
  "XCLDTHOLD"         : "-1.0",
}

MODD_RADn__   = { # config radiation
  "XDTRAD"            : "XTSTEP",
  "XDTRAD_CLONLY"     : "XTSTEP",
  "LCLEAR_SKY"        :".FALSE.",
  "NRAD_COLNBR"       : "1000",
  "NRAD_DIAG"         : "0",
  "CLW"               :"'RRTM'",
  "CAER"              :"'SURF'",
  "CAOP"              :"'CLIM'",
  "CEFRADL"           :"'MART'",
  "CEFRADI"           :"'LIOU'",
  "COPWSW"            : "'FOUQ'",
  "COPISW"            : "'EBCU'",
  "COPWLW"            : "'SMSH'",
  "COPILW"            : "'EBCU'",
  "XFUDG"             : "1.",
  "LAERO_FT"          :".FALSE.",
  "LFIX_DAT"          :".FALSE.",
}

MODD_PARAM_ECRAD__ = { # config radiation scheme
  "NSWSOLVER"         : "0",
  "NLWSOLVER"         : "0",
  "LSPEC_ALB"         : ".FALSE.",
  "LSPEC_EMISS"       : ".FALSE.",
  "SURF_TYPE"         : "'SNOW'",
  "NREG"              : "3",
  "NLWSCATTERING"     : "2",
  "NAERMACC"          : "0",
  "NOVLP"             : "1",
  "NLIQOPT"           : "3",
  "NICEOPT"           : "3",
  "NRADLP"            : "1",
  "NRADIP"            : "1",
  "XCLOUD_FRAC_STD"   : "1.0",
}

MODD_PARAM_LIMA__ = {  # config microphysics scheme
   "LPTSPLIT"         : ".TRUE.",
   "L_LFEEDBACKT"     : ".TRUE.",
   "L_NMAXITER"       : "5",
   "L_XMRSTEP"        : "0.005",
   "L_XTSTEP_TS"      : "20.",
   "YNUC"             : "1.0",
   "YALPHAC"          : "3.0",
   "YNUR"             : "2.0",
   "YALPHAR"          : "1.0",
   "LACTI"            : ".TRUE.",
   "OSEDC"            : ".TRUE.",
   "OACTIT"           : ".FALSE.",
   "LADJ"             : ".TRUE.",
   "LSPRO"            : ".FALSE.",
   "LKHKO"            : ".FALSE.",
   "ODEPOC"           : ".TRUE.",
   "LBOUND"           : ".FALSE.",
   "OACTTKE"          : ".TRUE.",
   "LKESSLERAC"       : ".FALSE.",
   "NMOM_C"           : "2",
   "NMOM_R"           : "2",
   "OVDEPOC"          : "0.02",
   "CINI_CCN"         : "'AER'",
   "CTYPE_CCN(:)"     : "'M'",
   "YAERDIFF"         : "0.0",
   "YAERHEIGHT"       : "2000.",
   "YFSOLUB_CCN"      : "1.0",
   "YACTEMP_CCN"      : "280.",
   "NMOD_CCN"         : "1",
   "LSCAV"            : ".FALSE.",
   "LAERO_MASS"       : ".FALSE.",
   "LCCN_HOM"         : ".TRUE.",
   "CCCN_MODES"       : "'COPT'",
   "XCCN_CONC(:)"     : "300.",
   "LHHONI"           : ".FALSE.",
   "LNUCL"            : ".TRUE.",
   "LSEDI"            : ".TRUE.",
   "YSNOW_T"          : ".FALSE.",
   "LMURAKAMI"        : ".TRUE.",
   "CPRISTINE_ICE_LIMA": "'PLAT'",
   "CHEVRIMED_ICE_LIMA": "'GRAU'",
   "XFACTNUC_DEP"     : "1.0",  
   "XFACTNUC_CON"     : "1.0",
   "NMOM_I"           : "2",
   "NMOM_S"           : "1",
   "NMOM_G"           : "1",
   "NMOM_H"           : "0",
   "NMOD_IFN"         : "1",
   "NIND_SPECIE"      : "1",
   "LMEYERS"          : ".FALSE.",
   "LIFN_HOM"         : ".TRUE.",
   "CIFN_SPECIES"     : "'PHILLIPS'",
   "CINT_MIXING"      : "'DM2'",
   "XIFN_CONC(:)"     : "100.",
   "NMOD_IMM"         : "0",
   "NPHILLIPS"        : "8",
   "LCIBU"            : ".FALSE.",
   "XNDEBRIS_CIBU"    : "50.0",
   "LRDSF"            : ".FALSE.",
}

MODD_PARAM_C2R2__ = {  # config cloud scheme ## CHECK DEFAULTS !!
    "HPARAM_CCN"      : "CPB",
    "HINI_CCN"        : "CCN",
    "XCHEN"           : "0.173E+09",
    "XKHEN"           : "1.403",
    "XMUHEN"          : "0.834",
    "XBETAHEN"        : "25.499",
    "LRAIN"           : ".FALSE.",
    "LSEDC"           : ".FALSE.",
}

MODD_BUDGET__  = { # compute budgets
  "CBUTYPE"           : "'NONE'",
  "NBUMOD"            : "1",
  "XBULEN"            : MODD_CONF__["XSEGLEN"],
  "XBUWRI"            : MODD_CONF__["XSEGLEN"],
  "NBUKL"             : "1",
  "NBUKH"             : "0",        
  "LBU_KCP"           : ".TRUE.",
  "NBUIL"             : "1",
  "NBUIH"             : "0",      
  "NBUJL"             : "1",
  "NBUJH"             : "0",          
  "LBU_ICP"           : ".TRUE.",
  "LBU_JCP"           : ".TRUE.",
  "NBUMASK"           : "1",
}

MODD_LES__     = { # compute horizontal statistics 
  "LLES_MEAN"           : ".FALSE.",
  "LLES_RESOLVED"       : ".FALSE.",
  "LLES_SUBGRID"        : ".FALSE.",
  "LLES_UPDRAFT"        : ".FALSE.",
  "LLES_DOWNDRAFT"      : ".FALSE.",
  "LLES_SPECTRA"        : ".FALSE.",
  "CLES_NORM_TYPE"      : "'NONE'",
  "CBL_HEIGHT_DEF"      : "'KE'",
  "XLES_TEMP_MEAN_STEP" : "3600.",
  "LLES_CART_MASK"      : ".FALSE.",
  "LLES_NEB_MASK"       : ".FALSE.",
  "LLES_CORE_MASK"      : ".FALSE.",
  "LLES_MY_MASK"        : ".FALSE.",
  "LLES_CS_MASK"        : ".FALSE.",
}

MODD_CONDSAMP__ = { # conditional sampling
  "LCONDSAMP"         : ".FALSE.",
  "NCONDSAMP"         : "3",
  "XRADIO(:)"         : "900.",
  "XSCAL(:)"          : "1.",
  "XHEIGHT_BASE"      : "100.",
  "XDEPTH_BASE"       : "100.",
  "XHEIGHT_TOP"       : "100.",
  "XDEPTH_TOP"        : "100.",
  "NFINDTOP"          : "0",
  "XTHVP"             : "0.25",
  "LTPLUS"            : ".TRUE.",
}

default_config = {
  "NAM_CONFIO": MODD_CONFIO__,
  "NAM_CONFZ": MODD_CONFZ__,
  "NAM_BACKUP": MODD_BACKUP__,
  "NAM_IDEAL_FLUX": SURF_IDEAL_FLUX__,
  "NAM_CONF": MODD_CONF__,
  "NAM_CONFn": MODD_CONFn__,
  "NAM_FRC" : MODD_FRC__,
  "NAM_LBCn" : MODD_LBCn__,
  "NAM_DYN" : MODD_DYN__,
  "NAM_DYNn" : MODD_DYNn__,
  "NAM_ADVn" : MODD_ADVn__,
  "NAM_PARAMn" : MODD_PARAMn__,
  "NAM_TURBn" : MODD_TURBn__,
  "NAM_RADn" : MODD_RADn__,
  "NAM_PARAM_ECRAD" : MODD_PARAM_ECRAD__,
  "NAM_PARAM_LIMA" : MODD_PARAM_LIMA__,
  "NAM_PARAM_C2R2" : MODD_PARAM_C2R2__,
  "NAM_BUDGET" : MODD_BUDGET__,
  "NAM_LES" : MODD_LES__,
  "NAM_CONDSAMP" : MODD_CONDSAMP__,
}
