#!/bin/sh
#SBATCH -J RUN_MESONH 
#SBATCH -N 30               # nodes number
#SBATCH -n 3840               # CPUs number (on all nodes) nb of cores xnb of nodes nb of  cores=(min(Nx)/8)^2 (ici 512/8)^2=4096 (/128=32) ici 30
#SBATCH -o output.eo%j
#SBATCH -e output.eo%j
#SBATCH -t 10:00:00        # time limit
#SBATCH -p normal256

ulimit -s unlimited
ulimit -c 0

# ---------------------------------------------------------
# VERSION de Meso-NH
# ---------------------------------------------------------
cp -f EXSEG1.nam_START EXSEG1.nam
. ~couvreux/MNH-V5-5-1/conf/profile_mesonh-LXifort-R8I4-MNH-V5-5-1-MPIAUTO-O2

export MPIRUN="Mpirun -np 3840"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#--
time ${MPIRUN} MESONH${XYZ}
#--


